#!name=MinhQuan
#!desc=Locket Gold

[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/phiminhquan2010/LocketGold/refs/heads/main/gold.js, requires-body=true, max-size=-1, timeout=120
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/phiminhquan2010/LocketGold/refs/heads/main/header.js, timeout=120

[MITM]
hostname = %APPEND% api.revenuecat.com